"use strict";
const $=id=>document.getElementById(id);
const els={track:$('trackCanvas'),graph:$('graphCanvas'),bars:$('barCanvas'),toggle:$('toggle'),reset:$('reset'),status:$('statusText'),hero:$('heroEquation'),motion:$('motionTitle'),graphTitle:$('graphTitle'),barsTitle:$('barsTitle'),quantities:$('quantities'),collisionKind:$('collisionKind'),collisionType:$('collisionType'),eField:$('eField'),forceField:$('forceField'),m2Field:$('m2Field'),v2Field:$('v2Field'),takeawayTitle:$('takeawayTitle'),takeawayText:$('takeawayText')};
const inputs=['m1','m2','force','v1','v2','restitution'].reduce((o,k)=>(o[k]=$(k),o),{});
let mode='work',running=false,last=0,accumulator=0;
const S={dt:.01,t:0,x1:0,x2:6,v1:2,v2:-1,collided:false,initialP:0,initialK:0,h:[]};

function values(){return Object.fromEntries(Object.entries(inputs).map(([k,e])=>[k,+e.value]));}
function reset(){const v=values();Object.assign(S,{t:0,x1:0,x2:6,v1:v.v1,v2:v.v2,collided:false,h:[]});S.initialP=v.m1*S.v1+v.m2*S.v2;S.initialK=.5*v.m1*S.v1**2+.5*v.m2*S.v2**2;running=false;last=0;setStatus();draw();}
function setStatus(){els.toggle.textContent=running?'Ⅱ Pause':'▶ Start';els.status.textContent=running?'Running':'Paused';els.status.parentElement.classList.toggle('running',running)}
function step(){const v=values();S.t+=S.dt;let F=0;if(mode==='work'){F=v.force;S.v1+=F/v.m1*S.dt;S.x1+=S.v1*S.dt}else if(mode==='impulse'){F=S.t<=2?v.force:0;S.v1+=F/v.m1*S.dt;S.x1+=S.v1*S.dt}else{const oldGap=S.x2-S.x1;S.x1+=S.v1*S.dt;S.x2+=S.v2*S.dt;const gap=S.x2-S.x1;if(!S.collided&&S.v1>S.v2&&oldGap>.6&&gap<=.6){const mid=(S.x1+S.x2)/2;S.x1=mid-.3;S.x2=mid+.3;collide(v);S.collided=true}}const p=v.m1*S.v1+v.m2*S.v2,K=.5*v.m1*S.v1**2+.5*v.m2*S.v2**2;S.h.push({t:S.t,x:S.x1,v1:S.v1,v2:S.v2,F,p,K});if(S.h.length>800)S.h.shift();}
function collide(v){const u1=S.v1,u2=S.v2,m1=v.m1,m2=v.m2;const e=els.collisionType.value==='elastic'?1:els.collisionType.value==='perfect'?0:v.restitution;S.v1=((m1-e*m2)*u1+(1+e)*m2*u2)/(m1+m2);S.v2=((m2-e*m1)*u2+(1+e)*m1*u1)/(m1+m2)}
function animate(ts){if(running){if(!last)last=ts;accumulator+=Math.min((ts-last)/1000,.05);last=ts;while(accumulator>=S.dt){step();accumulator-=S.dt}draw()}requestAnimationFrame(animate)}

function fit(canvas){const d=devicePixelRatio||1,r=canvas.getBoundingClientRect();if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d)}const c=canvas.getContext('2d');c.setTransform(d,0,0,d,0,0);return[c,r.width,r.height]}
function draw(){drawTrack();drawGraph();drawBars();drawQuantities()}
function drawTrack(){const[c,w,h]=fit(els.track);c.clearRect(0,0,w,h);const left=55,right=w-28,y=h*.68,toX=x=>left+(x+2)/12*(right-left);c.strokeStyle='#8493aa';c.lineWidth=3;c.beginPath();c.moveTo(left,y);c.lineTo(right,y);c.stroke();for(let x=-2;x<=10;x+=2){const px=toX(x);c.lineWidth=1;c.strokeStyle='#d8e0ec';c.beginPath();c.moveTo(px,28);c.lineTo(px,y+18);c.stroke();c.fillStyle='#718097';c.font='12px system-ui';c.textAlign='center';c.fillText(`${x} m`,px,y+35)}cart(c,toX(S.x1),y,'#1769e0','1',S.v1);if(mode==='collision')cart(c,toX(S.x2),y,'#ef6c32','2',S.v2);else{const v=values();if(Math.abs(v.force)>.01){c.strokeStyle='#12233f';c.fillStyle='#12233f';c.lineWidth=3;const a=toX(S.x1),dir=Math.sign(v.force),end=a+dir*55;c.beginPath();c.moveTo(a,y-50);c.lineTo(end,y-50);c.stroke();c.beginPath();c.moveTo(end,y-50);c.lineTo(end-dir*12,y-57);c.lineTo(end-dir*12,y-43);c.closePath();c.fill();c.textAlign='center';c.fillText(`F = ${v.force.toFixed(1)} N`,a,y-67)}}}
function cart(c,x,y,color,label,vel){c.fillStyle=color;c.strokeStyle='#12233f';c.lineWidth=2;c.beginPath();c.roundRect(x-30,y-30,60,30,5);c.fill();c.stroke();c.fillStyle='#12233f';for(const dx of[-17,17]){c.beginPath();c.arc(x+dx,y+5,6,0,Math.PI*2);c.fill()}c.font='700 13px system-ui';c.textAlign='center';c.fillStyle='#12233f';c.fillText(`m${label}   v${label}=${vel.toFixed(2)} m/s`,x,y-43)}

function axes(c,w,h,yLabel){const L=48,R=w-14,T=15,B=h-32;c.strokeStyle='#b8c5d6';c.lineWidth=1;c.beginPath();c.moveTo(L,T);c.lineTo(L,h-B);c.lineTo(w-R,h-B);c.stroke();c.fillStyle='#718097';c.font='11px system-ui';c.textAlign='center';c.fillText('time (s)',(L+w-R)/2,h-7);c.save();c.translate(13,(T+h-B)/2);c.rotate(-Math.PI/2);c.fillText(yLabel,0,0);c.restore();return{L,R,T,B,W:w-R-L,H:h-B-T}}
function drawGraph(){const[c,w,h]=fit(els.graph);c.clearRect(0,0,w,h);const a=axes(c,w,h,mode==='collision'?'velocity (m/s)':'scaled value');if(S.h.length<2)return;const series=mode==='collision'?[['v1','#1769e0'],['v2','#ef6c32']]:[['x','#1769e0'],['v1','#0c8b82'],['F','#ef6c32']];const vals=S.h.flatMap(p=>series.map(([k])=>p[k])),mn=Math.min(-.2,...vals),mx=Math.max(.2,...vals),span=mx-mn||1,t0=S.h[0].t,t1=S.h.at(-1).t||1;for(const[k,color]of series){c.strokeStyle=color;c.lineWidth=2;c.beginPath();S.h.forEach((p,i)=>{const x=a.L+(p.t-t0)/(t1-t0||1)*a.W,y=a.T+(mx-p[k])/span*a.H;i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke()}c.font='11px system-ui';let x=a.L+8;for(const[k,color]of series){c.fillStyle=color;c.fillRect(x,a.T+4,12,3);c.fillStyle='#52617a';c.textAlign='left';c.fillText(k==='x'?'x₁':k.replace('v','v'),x+16,a.T+9);x+=55}}
function drawBars(){const[c,w,h]=fit(els.bars);c.clearRect(0,0,w,h);const v=values();let data;if(mode==='work'){const Ki=.5*v.m1*v.v1**2,K=.5*v.m1*S.v1**2,W=v.force*S.x1;data=[['ΔK',K-Ki],['Work',W]]}else if(mode==='impulse'){const pi=v.m1*v.v1,p=v.m1*S.v1,J=S.h.reduce((n,q)=>n+q.F*S.dt,0);data=[['Δp',p-pi],['Impulse',J]]}else{const p=v.m1*S.v1+v.m2*S.v2,K=.5*v.m1*S.v1**2+.5*v.m2*S.v2**2;data=[['p initial',S.initialP],['p current',p],['K initial',S.initialK],['K current',K]]}const max=Math.max(1,...data.map(d=>Math.abs(d[1]))),base=h-45,top=18,bw=Math.min(55,(w-45)/data.length*.55),gap=(w-45)/data.length;data.forEach((d,i)=>{const x=35+i*gap+(gap-bw)/2,val=d[1],bh=Math.abs(val)/max*(base-top-18),y=val>=0?base-bh:base;c.fillStyle=i%2?'#0c8b82':'#1769e0';c.fillRect(x,y,bw,bh);c.fillStyle='#12233f';c.font='700 11px system-ui';c.textAlign='center';c.fillText(val.toFixed(2),x+bw/2,val>=0?y-5:y+bh+13);c.fillStyle='#61708a';c.font='10px system-ui';c.fillText(d[0],x+bw/2,h-18)});c.strokeStyle='#b8c5d6';c.beginPath();c.moveTo(25,base);c.lineTo(w-10,base);c.stroke()}
function drawQuantities(){const v=values();let q;if(mode==='work'){const Ki=.5*v.m1*v.v1**2,K=.5*v.m1*S.v1**2,W=v.force*S.x1;q=[['Elapsed time',`${S.t.toFixed(2)} s`],['Displacement',`${S.x1.toFixed(2)} m`],['Velocity',`${S.v1.toFixed(2)} m/s`],['Work',`${W.toFixed(2)} J`],['Change in K',`${(K-Ki).toFixed(2)} J`],['Current K',`${K.toFixed(2)} J`]]}else if(mode==='impulse'){const pi=v.m1*v.v1,p=v.m1*S.v1,J=S.h.reduce((n,x)=>n+x.F*S.dt,0);q=[['Force now',`${S.t<=2?v.force:0} N`],['Force duration','2.00 s'],['Impulse',`${J.toFixed(2)} N·s`],['Change in p',`${(p-pi).toFixed(2)} kg·m/s`],['Current p',`${p.toFixed(2)} kg·m/s`],['Elapsed time',`${S.t.toFixed(2)} s`]]}else{const p=v.m1*S.v1+v.m2*S.v2,K=.5*v.m1*S.v1**2+.5*v.m2*S.v2**2,e=els.collisionType.value==='elastic'?1:els.collisionType.value==='perfect'?0:v.restitution;q=[['Restitution',e.toFixed(2)],['Collision',S.collided?'Occurred':'Not yet'],['Total p',`${p.toFixed(3)} kg·m/s`],['Initial p',`${S.initialP.toFixed(3)} kg·m/s`],['Total K',`${K.toFixed(3)} J`],['K retained',`${(100*K/S.initialK).toFixed(1)}%`],['v₁',`${S.v1.toFixed(2)} m/s`],['v₂',`${S.v2.toFixed(2)} m/s`]]}els.quantities.innerHTML=q.map(([a,b])=>`<div class="quantity"><small>${a}</small><b>${b}</b></div>`).join('')}

function configure(){document.querySelectorAll('.mode-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));const col=mode==='collision';els.collisionKind.classList.toggle('hidden',!col);els.m2Field.classList.toggle('hidden',!col);els.v2Field.classList.toggle('hidden',!col);els.forceField.classList.toggle('hidden',col);els.eField.classList.toggle('hidden',!col||els.collisionType.value!=='partial');if(mode==='work'){els.hero.innerHTML='W<sub>net</sub> = ΔK';els.motion.textContent='Work changes kinetic energy';els.graphTitle.textContent='Position, velocity & force';els.barsTitle.textContent='Work-energy comparison';els.takeawayTitle.textContent='Work-energy theorem';els.takeawayText.textContent='Net work equals the change in kinetic energy—not necessarily the final kinetic energy itself.'}else if(mode==='impulse'){els.hero.innerHTML='J = Δp';els.motion.textContent='Impulse changes momentum';els.graphTitle.textContent='Position, velocity & force';els.barsTitle.textContent='Impulse-momentum comparison';els.takeawayTitle.textContent='Impulse-momentum theorem';els.takeawayText.textContent='The area under the force-versus-time graph equals the change in momentum.'}else{els.hero.innerHTML='p<sub>before</sub> = p<sub>after</sub>';els.motion.textContent='Momentum during a 1D collision';els.graphTitle.textContent='Cart velocities';els.barsTitle.textContent='Before & after comparison';els.takeawayTitle.textContent='Collision principle';els.takeawayText.textContent='Momentum is conserved in every isolated collision. Kinetic energy is conserved only in an elastic collision.'}reset()}
function updateOutputs(){const units={m1:' kg',m2:' kg',force:' N',v1:' m/s',v2:' m/s',restitution:''};for(const[k,e]of Object.entries(inputs))$(`${k==='restitution'?'e':k}Out`).textContent=(+e.value).toFixed(k==='force'?1:2)+units[k]}
document.querySelectorAll('.mode-tabs button').forEach(b=>b.addEventListener('click',()=>{mode=b.dataset.mode;configure()}));els.toggle.addEventListener('click',()=>{running=!running;last=0;setStatus()});els.reset.addEventListener('click',reset);els.collisionType.addEventListener('change',configure);Object.values(inputs).forEach(e=>e.addEventListener('input',()=>{updateOutputs();reset()}));window.addEventListener('resize',draw);updateOutputs();configure();requestAnimationFrame(animate);
